Unlock state

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -47,33 +47,33 @@ jobs:
         cd ./environments/personal
         terraform init
     
-    - name: Terraform plan
-      id: plan
-      # if: github.event_name == 'pull_request'
-      run: |
-        cd ./environments/personal
-        terraform plan -input=false
-      continue-on-error: true
+    # - name: Terraform plan
+    #   id: plan
+    #   # if: github.event_name == 'pull_request'
+    #   run: |
+    #     cd ./environments/personal
+    #     terraform plan -input=false
+    #   continue-on-error: true
       
-    - name: Terraform Plan Status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+    # - name: Terraform Plan Status
+    #   if: steps.plan.outcome == 'failure'
+    #   run: exit 1
     
-    - name: Manual Approval
-      uses: trstringer/manual-approval@v1
-      with:
-        secret: ${{ github.TOKEN }}
-        approvers: kandlagifari
-        minimum-approvals: 1
-        issue-title: "Deploying to Personal Environment"
-        issue-body: "Review the terraform plan, then approve or deny the deployment to Personal Environment."
-        exclude-workflow-initiator-as-approver: false
+    # - name: Manual Approval
+    #   uses: trstringer/manual-approval@v1
+    #   with:
+    #     secret: ${{ github.TOKEN }}
+    #     approvers: kandlagifari
+    #     minimum-approvals: 1
+    #     issue-title: "Deploying to Personal Environment"
+    #     issue-body: "Review the terraform plan, then approve or deny the deployment to Personal Environment."
+    #     exclude-workflow-initiator-as-approver: false
 
-    - name: Terraform Apply
-      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-      run: |
-        cd ./environments/personal
-        terraform apply -auto-approve -input=false
+    # - name: Terraform Apply
+    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+    #   run: |
+    #     cd ./environments/personal
+    #     terraform apply -auto-approve -input=false
     
     # - name: Terraform destroy
     #   id: destroy
@@ -86,3 +86,9 @@ jobs:
     #   run: |
     #     cd ./environments/personal
     #     terraform state list
+
+    - name: Terraform force unlock
+      id: unlock
+      run: |
+        cd ./environments/personal
+        terraform force-unlock -force bcee4658-f482-f43b-7648-f765cd512ea4
